project:
  type: book
  output-dir: docs

# https://quarto.org/docs/reference/projects/books.html

book:
  title: "Biodiverse Spatial Conditions"
  author: "Shawn W Laffan"
  date: "2026-10-07"
  date-format: iso
  chapters:
    - index.qmd
    - overview.qmd
    - spatial_conditions.qmd
    - variables.qmd
  output-file: "Biodiverse-Spatial-Conditions"
  downloads: [pdf]
  repo-url: https://github.com/biogeospatial/biodiverse-spatial-conditions

  
format:
  html:
    theme: zephyr
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-title: "Page contents"
    number-sections: true
    number-depth: 2
    link-external-newwindow: true
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    papersize: a4

editor: source
